name: Wait 60 Seconds

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  wait-and-pass:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v4
        with:
          # Explicitly use github.ref which is refs/pull/:number/merge for PRs
          ref: ${{ github.ref }}

      - name: Display commit info
        run: |
          echo "Checking out refspec: ${{ github.ref }}"
          echo "Current commit: $(git rev-parse HEAD)"

      - name: Check PR info via GitHub API
        if: github.event_name == 'pull_request'
        run: |
          echo "Querying PR #${{ github.event.pull_request.number }} for status information"
          echo ""

          # Get PR details including status checks
          PR_DATA=$(curl -s -H "Authorization: token ${{ github.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}")

          echo "Merge commit SHA:"
          echo "$PR_DATA" | jq -r '.merge_commit_sha'

          echo "PR Head SHA (where statuses are posted):"
          echo "$PR_DATA" | jq -r '.head.sha'

          echo ""
          echo "PR Base SHA:"
          echo "$PR_DATA" | jq -r '.base.sha'

          echo ""
          echo "Mergeable state:"
          echo "$PR_DATA" | jq -r '.mergeable_state'

          echo ""
          echo "Now checking statuses on the HEAD SHA..."
          HEAD_SHA=$(echo "$PR_DATA" | jq -r '.head.sha')

          echo "Full response:"
          echo "$PR_DATA" | jq '.'

          STATUS_DATA=$(curl -s -H "Authorization: token ${{ github.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/commits/$HEAD_SHA/status")

          echo ""
          echo "Statuses for HEAD SHA ($HEAD_SHA):"
          echo "$STATUS_DATA" | jq -r '.statuses[]? | "\(.context): \(.state) - \(.description)"'

          echo ""
          echo "Workflow context information:"
          echo "github.sha (merge commit): ${{ github.sha }}"
          echo "github.event.pull_request.head.sha (PR head): ${{ github.event.pull_request.head.sha }}"

      - name: Query commit status info
        if: github.event_name == 'pull_request'
        run: |
          echo "Querying PR #${{ github.event.pull_request.number }} for status information"
          echo ""

          STATUS_DATA=$(curl -s -H "Authorization: token ${{ github.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/commits/$HEAD_SHA/status")

          echo ""
          echo "Statuses for HEAD SHA ($HEAD_SHA):"
          echo "$STATUS_DATA" | jq -r '.statuses[]? | "\(.context): \(.state) - \(.description)"'

          echo ""
          echo "Workflow context information:"
          echo "github.sha (merge commit): ${{ github.sha }}"
          echo "github.event.pull_request.head.sha (PR head): ${{ github.event.pull_request.head.sha }}"

      - name: Wait for 3 seconds
        run: sleep 3

      - name: Success
        run: echo "✅ Waited 3 seconds successfully!"

  # manual-approval:
  #   runs-on: ubuntu-latest
  #   needs: wait-and-pass
  #   if: github.event_name == 'pull_request'

  #   steps:
  #     - name: Await Manual Approval
  #       uses: trstringer/manual-approval@v1
  #       with:
  #         secret: ${{ github.TOKEN }}
  #         approvers: jonathanly
  #         minimum-approvals: 1
  #         exclude-workflow-initiator-as-approver: false
  #         fail-on-denial: true
  #         issue-title: "Manual Approval Required for deployment"
  #         issue-body: "Please approve or deny the deployment."

  # # Get the combined status for this commit
  # RESPONSE=$(curl -s -H "Authorization: token ${{ github.token }}" \
  #      -H "Accept: application/vnd.github.v3+json" \
  #      "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status")

  # echo "Full response:"
  # echo "$RESPONSE" | jq '.'

  # echo ""
  # echo "SHA from status:"
  # echo "$RESPONSE" | jq -r '.sha'

  # echo ""
  # echo "State:"
  # echo "$RESPONSE" | jq -r '.state'

  # echo ""
  # echo "Status contexts:"
  # echo "$RESPONSE" | jq -r '.statuses[]? | "\(.context): \(.state)"'
