name: Wait 60 Seconds

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  wait-and-pass:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v4
        # By default on pull_request events, this checks out the merge commit
        # (refs/pull/:prNumber/merge) which is what you want

      - name: Display commit info
        run: |
          echo "Current commit: $(git rev-parse HEAD)"
          echo "This is the merge commit of PR into base branch"

      - name: Wait for 10 seconds
        run: sleep 10

      - name: Success
        run: echo "✅ Waited 10 seconds successfully!"

manual-approval:
  runs-on: ubuntu-latest
  needs: wait-and-pass
  environment: production  # This environment requires manual approval

  steps:
    - name: Approved
      run: echo "🎉 Workflow was manually approved!"
