name: Wait 60 Seconds

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  wait-and-pass:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v4
        with:
          # Explicitly use github.ref which is refs/pull/:number/merge for PRs
          ref: ${{ github.ref }}

      - name: Display commit info
        run: |
          echo "Checking out refspec: ${{ github.ref }}"
          echo "Current commit: $(git rev-parse HEAD)"

      - name: Check commit status via GitHub API
        run: |
          echo "Querying commit status for SHA: ${{ github.sha }}"

          # Get the combined status for this commit
          curl -s -H "Authorization: token ${{ github.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status" \
               | jq -r '.sha, .state, .statuses[] | .context, .target_url'

          echo ""
          echo "Commit SHA from context: ${{ github.sha }}"
          echo "Event pull request head SHA: ${{ github.event.pull_request.head.sha }}"

      - name: Wait for 3 seconds
        run: sleep 3

      - name: Success
        run: echo "✅ Waited 3 seconds successfully!"

  # manual-approval:
  #   runs-on: ubuntu-latest
  #   needs: wait-and-pass
  #   if: github.event_name == 'pull_request'

  #   steps:
  #     - name: Await Manual Approval
  #       uses: trstringer/manual-approval@v1
  #       with:
  #         secret: ${{ github.TOKEN }}
  #         approvers: jonathanly
  #         minimum-approvals: 1
  #         exclude-workflow-initiator-as-approver: false
  #         fail-on-denial: true
  #         issue-title: "Manual Approval Required for deployment"
  #         issue-body: "Please approve or deny the deployment."
