name: Wait 60 Seconds

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  wait-and-pass:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v4
        # By default on pull_request events, this checks out the merge commit
        # (refs/pull/:prNumber/merge) which is what you want
      
      - name: Display commit info
        run: |
          echo "Current commit: $(git rev-parse HEAD)"
          echo "This is the merge commit of PR into base branch"
      
      - name: Wait for 60 seconds
        run: sleep 60
      
      - name: Success
        run: echo "✅ Waited 60 seconds successfully!"
